version: '3.9'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - '8086:8086'
    # network_mode: host
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      # - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      # - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      # - INFLUXDB_HTTP_AUTH_ENABLED=false
      # - INFLUXDB_DATA_ENGINE=tsm1
      # - INFLUXDB_REPORTING_DISABLED=false
      # - 'PORT': '8086'
      # - 'HOST': 'localhost'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1G'
    # cpus: '2'
    # mem_limit: 1G

  grafana:
    image: grafana/grafana:latest
    # network_mode: host
    ports:
      - "3000:3000"
    networks:
      - grafana

    volumes:
      - grafana-storage:/var/lib/grafana
      - ../grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      # - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      # - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      # - 'PORT': '3000'
      # - 'HOST': 'localhost'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
    # cpus: '0.5'
    # mem_limit: 500M

  api:
    image: vntura/api_users:1.0
    environment:
      - NODE_ENV=production
    ports:
      - "3333:3333"
    # cpus: '0.5'
    # mem_limit: 512M
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512M'

  k6:
    image: grafana/k6:latest
    # network_mode: host
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://localhost:8086/db0
      # - K6_INFLUXDB_ORGANIZATION=k6io
      # - K6_INFLUXDB_BUCKET=demo
      # - K6_INFLUXDB_INSECURE=true
      - K6_INFLUXDB_PUSH_INTERVAL=2s
    volumes:
      - ./tests:/tests
    entrypoint: ["k6"]

volumes:
  influxdb-storage:
  grafana-storage:
  tests:
