version: '3.9'

services:
  influxdb:
    image: influxdb:1.8
    network_mode: host
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    cpus: '2'
    mem_limit: 1G

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      # - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      # - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    cpus: '0.5'
    mem_limit: 500M

  api:
    image: vntura/api_users:1.0
    environment:
      - NODE_ENV=production
    ports:
      - "3333:3333"
    cpus: '0.5'
    mem_limit: 512M

  k6:
    image: grafana/k6:latest
    network_mode: host
    environment:
      - K6_OUT=influxdb=http://localhost:8086
      # - K6_INFLUXDB_ORGANIZATION=k6io
      # - K6_INFLUXDB_BUCKET=demo
      # - K6_INFLUXDB_INSECURE=true
      - K6_INFLUXDB_PUSH_INTERVAL=2s

volumes:
  influxdb-storage:
  grafana-storage:
  tests:
