version: '3.9'

services:
  influxdb:
    image: influxdb:1.8
    network_mode: host
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0; CREATE DATABASE db0;
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

  grafana:
    image: grafana/grafana
    # ports:
    #   - '3000:3000'
    # networks:
    #   - k6
    network_mode: host
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5G'

  k6:
    image: grafana/k6
    # networks:
    #   - k6
    # ports:
    #   - "6565:6565"
    network_mode: host
    environment:
      - K6_INFLUXDB_PUSH_INTERVAL=2s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1G'

  api:
    image: vntura/api_users:1.0
    environment:
      - NODE_ENV:production
    # networks:
    #   - k6
    # ports:
    #   - "3333:3333"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  influxdb-storage:
  grafana-storage:
  tests:
